import LoginPageLayout from "@/src/components/LoginPageLayout/LoginPageLayout";

import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Login Page",
  description: "Generated by Next.js",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <LoginPageLayout>{children}</LoginPageLayout>;
}
