import { Metadata } from "next";
import StyledComponentsRegistry from "../lib/registry";
import "../styles/globals.css";
import "../styles/rdt-styles.css"; // Styles React Date Time
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

import Fonts from "../lib/FontsFamily";
import Providers from "../components/Providers";

export const metadata: Metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

interface IProps {
  children: React.ReactNode;
}

async function RootLayout({ children }: IProps) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <Fonts />
      </head>
      <body>
        <div id="modal-root"></div>
        <Providers>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </Providers>
      </body>
    </html>
  );
}

export default RootLayout;
