const defaultColors = {
  white: "var(--white)",
  primaryText: "var(--primary-text)",
  primaryBtn: "var(--primary-btn)",
  primaryBgBtn: "var(--primary-bg-btn)",
  hoverBgBtn: "var(--hover-bg-btn)",
  secondaryBtn: "var(--secondary-btn)",
  secondaryBgBtn: "var(--secondary-bg-btn)",
  primaryPasswordIndicator: "var(--primary-password-indicator)",
  secondaryPasswordIndicator: "var(--secondary-password-indicator)",
  navIconBg: "var(--nav-icon-bg)",
  navIconBgActive: "var(--nav-icon-bg-active)",
  expense: "var(--expense)",
  basicStat: "var(--basic-stat)",
  productsStat: "var(--products-stat)",
  carStat: "var(--car-stat)",
  selfStat: "var(--self-stat)",
  childrenStat: "var(--children-stat)",
  houseStat: "var(--house-stat)",
  educationStat: "var(--education-stat)",
  leisureStat: "var(--leisure-stat)",
  otherStat: "var(--other-stat)",
};

export const colors = {
  LIGHT: {
    ...defaultColors,
    primaryBg: "var(--primary-bg-lgt)",
    secondaryBg: "var(--secondary-bg-lgt)",
    loginPageBg: "var(--loginPage-bg-lgt)",
    secondaryText: "var(--secondary-text-lgt)",
    secondaryDarkText: "var(--secondary-dark-text-lgt)",
    secondaryLightText: "var(--secondary-light-text-lgt)",
    gradient: "linear-gradient(rgba(47, 48, 58, 0),rgba(47, 48, 58, 0))",
  },

  DARK: {
    ...defaultColors,
    primaryBg: "var(--primary-bg-drk)",
    secondaryBg: "var(--secondary-bg-drk)",
    loginPageBg: "var(--loginPage-bg-drk)",
    secondaryText: "var(--secondary-text-drk)",
    secondaryDarkText: "var(--secondary-dark-text-drk)",
    secondaryLightText: "var(--secondary-light-text-drk)",
    gradient: "linear-gradient(rgba(47, 48, 58, 0.35),rgba(47, 48, 58, 0.35))",
  },
};

// const defaultColors = {
//   white: "#FFFFFF",
//   primaryText: "#000000",
//   primaryBtn: "#FFFFFF",
//   primaryBgBtn: "#24CCA7",
//   hoverBgBtn: "#2be2ba",
//   secondaryBtn: "#4A56E2",
//   secondaryBgBtn: "transparent",
//   primaryPasswordIndicator: "#24CCA7",
//   secondaryPasswordIndicator: "#E5F1EF",
//   navIconBg: "#6E78E8",
//   navIconBgActive: "#4A56E2",
//   expense: "#FF6596",
//   basicStat: "#FED057",
//   productsStat: "#FFD8D0",
//   carStat: "#FD9498",
//   selfStat: "#C5BAFF",
//   childrenStat: "#2d38be",
//   houseStat: "#4A56E2",
//   educationStat: "#81E1FF",
//   leisureStat: "#24CCA7",
//   otherStat: "#00AD84",
// };

// export const colors = {
//   LIGHT: {
//     ...defaultColors,
//     primaryBg: "#FFFFFF",
//     secondaryBg: "rgba(255, 255, 255, 0.4)",
//     loginPageBg: "#E7EAF2",
//     secondaryText: "#787272",
//     secondaryDarkText: "blue",
//     secondaryLightText: "#E0E0E0",
//     gradient: "linear-gradient(rgba(47, 48, 58, 0),rgba(47, 48, 58, 0))",
//   },

//   DARK: {
//     ...defaultColors,
//     primaryBg: "#38398F",
//     secondaryBg: "#9B91C7",
//     loginPageBg: "#685AA2",
//     secondaryText: "#ffffff",
//     secondaryDarkText: "red",
//     secondaryLightText: "#ECEAEA",
//     gradient: "linear-gradient(rgba(47, 48, 58, 0.35),rgba(47, 48, 58, 0.35))",
//   },
// };
