import { Metadata } from "next";
import DashBoardLayout from "@/src/components/DashBoardLayout/DashBoardLayout";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by Next.js",
};

export default function HomeLayout({children} : {children: React.ReactNode}) {
  return <>{children}</>;
  // return <DashBoardLayout>{children}</DashBoardLayout>;
}
