import { Metadata } from "next";
import DashBoardLayout from "@/src/components/DashBoardLayout/DashBoardLayout";
import Header from "@/src/components/Header/Header";
import ModalLogOut from "@/src/components/ModalLogOut/ModalLogOut";
import ModalBox from "@/src/components/ModalWindow/ModalBox";
import SideBar from "@/src/components/SideBar/SideBar";
import Navigation from "@/src/components/Navigation/Navigation";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by Next.js",
};

export default function HomeLayout({children}: {children: React.ReactNode}) {
  return (
    <>
      <Header />
      <DashBoardLayout>
      {/* <SideBar>
        <Navigation />
      </SideBar> */}
        {children}
      </DashBoardLayout>

      {/* <ModalBox modalName="logout">
        <ModalLogOut />
      </ModalBox> */}
    </>
  );
  // return <DashBoardLayout>{children}</DashBoardLayout>;
}
