import { Metadata } from "next";
import Header from "@/src/components/Header";
import DashBoardLayout from "@/src/components/DashBoardLayout";
import AnimateHeader from "@/src/components/AnimateHeader/AnimateHeader";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by Next.js",
};

export default function HomeLayout({children}: {children: React.ReactNode}) {
  return (
    <>
    <Link
        style={{ color: "red", fontSize: 20 }}
        href={"/"}
      >
        Main
      </Link>
      {/* <AnimateHeader> */}
        <Header />
      {/* </AnimateHeader> */}

      <DashBoardLayout>
        {children}
      </DashBoardLayout>
    </>
  );
}
